# Generated by Django 4.0.4 on 2022-10-15 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobpost', models.TextField()),
                ('jobdesc', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
