# Generated by Django 4.0.4 on 2022-10-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.TextField()),
                ('course', models.TextField()),
                ('date', models.DateField()),
                ('venue', models.TextField()),
                ('eventtime', models.TextField()),
            ],
        ),
    ]
