# Generated by Django 4.0.4 on 2022-10-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_participants_eventid_participants_evname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participants',
            name='evname',
        ),
        migrations.AlterField(
            model_name='participants',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
