# Generated by Django 4.0.4 on 2022-10-16 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_participants_course_remove_participants_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participants',
            name='eventid',
            field=models.TextField(blank=True, null=True),
        ),
    ]
