# Generated by Django 4.0.4 on 2022-10-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_participants_eventid'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='role',
            field=models.TextField(blank=True),
        ),
    ]
